version: 2.1
jobs:
  build:
    docker:
      # new all-in-one docker image
      - image: fr3akyphantom/droid-builder:latest
    environment:
      MANIFEST_BRANCH: 'android-7.1'
      VERSION: '2.9.1'
      MAINTAINER: '@ErwinAbs'
      VENDOR: 'sony'
      CODENAME: 'kagura'
      BUILD_LUNCH: 'omni_kagura-eng'
      PB_OFFICIAL: 'true'
      CHANGELOG: " - Initial build"
    working_directory: /home/builder/pitchblack
    steps: 
      - checkout
      - run:
          name: AIO Build
          command: |
            echo "Set GitAuth Infos too"
            git config --global user.email $GitHubMail
            git config --global user.name $GitHubName
            git config --global color.ui true
            wget -q https://raw.githubusercontent.com/PitchBlackRecoveryProject/vendor_utils/pb/build.sh
            source build.sh
workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          filters:
            branches:
              only: android-7.1
          context: org-global
