version: 2.1
jobs:
  build:
    docker:
      # new all-in-one docker image
      - image: fr3akyphantom/droid-builder:latest
    environment:
      MANIFEST_BRANCH: 'android-9.0'
      VERSION: '3.0.0'
      VENDOR: 'sony'
      CODENAME: 'kagura'
      BUILD_LUNCH: 'omni_kagura-eng'
      # Remove the following when Publishing Official
      TEST_BUILD: 'true'
      # Only for Official Build, uncomment following
      #PB_OFFICIAL: 'true'
      MAINTAINER: 'Erwin Abu Bakar Sidik'
      CHANGELOG: |
        - Update based 3.5.0
        - Improve translate
        - Added support terminal from file manager
        - Nuked SuperSU
        - Update lock pattern types for android 11
        - Fixed Codename Changer
        - Misc
    working_directory: /home/builder/pitchblack
    steps:
      - run:
          name: AIO Build
          command: |
            echo "Set GitAuth Infos too"
            git config --global user.email $GitHubMail
            git config --global user.name $GitHubName
            git config --global color.ui true
            wget -q https://raw.githubusercontent.com/PitchBlackRecoveryProject/vendor_utils/pb/build.sh
            source build.sh
workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          context: org-global
